mqtt:
  enabled: true
  host: mqtt
  port: 1883
  user: ''
  password: ''
  topic_prefix: frigate

lpr:
  enabled: True

objects:
  track:
    - person

go2rtc:
  streams:
    cam1:
      - rtsp://USERNAME:PASSWORD@IP_ADDRESS:554/stream1
    cam1_sub:
      - rtsp://USERNAME:PASSWORD@IP_ADDRESS:554/stream2
    cam360:
      - rtsp://USERNAME:PASSWORD@IP_ADDRESS:554/stream1
    cam360_sub:
      - rtsp://USERNAME:PASSWORD@IP_ADDRESS:554/stream2

cameras:
  cam1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam1_sub
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
    record:
      enabled: true
      continuous:
        days: 3
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
      quality: 80

  cam360:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam360
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam360_sub
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
    record:
      enabled: true
      continuous:
        days: 3
    onvif:
      host: IP_ADDRESS
      port: 2020
      user: USERNAME
      password: PASSWORD
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
      quality: 80

version: 0.17-0
